# https://starship.rs/config/

"$schema" = "https://starship.rs/config-schema.json"

[character]
format = "[ğŸ±](purple) "

[cmd_duration]
format = "| [$duration]($style) "

[git_branch]
ignore_branches = ["main"]

[git_status]
disabled = true

[nodejs]
symbol = "[â¬¢](bold green) "
